[server]
headless = true
port = 8501
enableCORS = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false
# .streamlit/secrets.toml
DATABASE_URL = "postgresql://postgres:Urji@2030@host:port/database"
